# Generated by Django 3.1.2 on 2020-11-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='who_added',
            field=models.CharField(default='Westerny', max_length=64),
        ),
        migrations.AddField(
            model_name='movie',
            name='who_added',
            field=models.CharField(default='Westerny', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='who_added',
            field=models.CharField(default='Westerny', max_length=64),
        ),
    ]
