# Generated by Django 3.1.2 on 2020-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0002_auto_20201102_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
