# Generated by Django 3.1.2 on 2020-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0003_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director', to='westerny_app.Person'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screenplay',
        ),
        migrations.AddField(
            model_name='movie',
            name='screenplay',
            field=models.ManyToManyField(related_name='screenplay', to='westerny_app.Person'),
        ),
    ]
