# Generated by Django 3.1.2 on 2020-12-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0004_auto_20201102_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(default='', null=True),
        ),
    ]
