# Generated by Django 3.1.2 on 2021-01-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0005_genre_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='music',
            field=models.ManyToManyField(related_name='music', to='westerny_app.Person'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='westerny_app.movie'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='persons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='westerny_app.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='westerny_app.year'),
        ),
    ]
