# Generated by Django 3.1.2 on 2021-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0007_auto_20210104_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_description',
            field=models.TextField(max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(max_length=4, unique=True),
        ),
    ]
