# Generated by Django 3.1.2 on 2021-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0011_auto_20210108_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'kawalerzysta'), (2, 'kapral'), (3, 'sierżant'), (4, 'porucznik'), (5, 'kapitan'), (6, 'major'), (7, 'pułkownik'), (8, 'generał')], max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_accepted',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_accepted',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_accepted',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
