# Generated by Django 3.1.2 on 2021-01-10 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('westerny_app', '0012_auto_20210109_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64)),
                ('link', models.URLField(unique=True)),
                ('article_adde_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_article',
            field=models.ManyToManyField(default=None, to='westerny_app.Article'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_article',
            field=models.ManyToManyField(default=None, to='westerny_app.Article'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_article',
            field=models.ManyToManyField(default=None, to='westerny_app.Article'),
        ),
    ]
