# Generated by Django 3.1.2 on 2021-01-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0015_auto_20210112_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'kawalerzysta'), (2, 'kapral'), (3, 'sierżant'), (4, 'porucznik'), (5, 'kapitan'), (6, 'major'), (7, 'pułkownik'), (8, 'generał')], max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='westerny_app.rank'),
        ),
    ]
