# Generated by Django 3.1.2 on 2021-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0016_auto_20210112_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[(1, 'Kawalerzysta'), (2, 'Kapral'), (3, 'Sierżant'), (4, 'Porucznik'), (5, 'Kapitan'), (6, 'Major'), (7, 'Pułkownik'), (8, 'Generał'), (9, 'Gubernator')], max_length=32, unique=True),
        ),
    ]
