# Generated by Django 3.1.2 on 2021-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0017_auto_20210112_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
