# Generated by Django 3.1.2 on 2021-01-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0024_personmovie_personmovie_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ManyToManyField(default=None, related_name='cinema', to='westerny_app.Person'),
        ),
    ]
