# Generated by Django 3.1.2 on 2021-01-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0027_userrank_promotion_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='org_title',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
