# Generated by Django 3.1.2 on 2021-01-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westerny_app', '0028_auto_20210125_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_rating',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
