# Generated by Django 3.1.2 on 2021-02-13 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('westerny_app', '0032_movie_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watchlist',
            field=models.ManyToManyField(default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
